modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/OpticManager/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="opticmanager"
    logoFile="opticmanager.png"
    version="1.3.2"
    displayName="OpticManager"
    displayURL="https://modrinth.com/mod/opticmanager"
    authors="CreativeMD"
    description='''Sync client side configurations. Modify length of day and night.'''

[[dependencies.opticmanager]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.10.22"

