modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/OpticManager/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="opticmanager"
    iconFile="opticmanager.png"
    version="1.3.6"
    displayName="OpticManager"
    displayURL="https://modrinth.com/mod/opticmanager"
    authors="CreativeMD"
    description='''Sync client side configurations. Modify length of day and night.'''

[[dependencies.opticmanager]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.6-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.14.0,)"

[[mixins]]
   config="opticmanager.mixins.json"

